import {page,escape} from '../views.js';

export function standalonePage(config,section) {
  const operator=escape(config.operatorName),issuer=escape(config.issuer);
  if(config.accountSource==='frrn' && ['about','home'].includes(section)) return page('Your FRRN account, connected',`<section class="narrow"><h1>Your FRRN account, connected</h1><p>FRRN holds your account and community membership approvals. Unanym reads current approvals and keeps your choices for each website. There is no second account or approval list here.</p><p>You choose your name and which memberships to share. ${operator} signs the statements and holds the identity keys. These are operator assertions about authorised organiser decisions, not organisation-held signatures or proof of training or safety.</p><p>Disconnecting stops new access. Websites may retain information already received. FRRN account deletion removes the linked identity records during the hourly cleanup; operator backup retention still applies.</p><a href="/identity/sites">My connections</a> · <a href="/account">My FRRN account</a></section>`,config);
  const pages={
    home:['Your communities. Your choice.',`<p class="lead">One email sign-in. A name and sharing choice for each website.</p><div class="actions"><a class="button" href="/identity/account">Your account</a><a class="button secondary" href="/identity/sites">Your connections</a></div><h2>Choose what crosses</h2><p>A website receives your chosen name and a separate identifier. Share an approved membership if you want to. Your email stays with ${operator}.</p><p>Each website decides who can access its services.</p>`],
    about:['How your information is handled',`<h2>Your account</h2><p>${operator} runs this service. It stores your email, sign-in sessions, organisation approvals and website sharing records. Email codes expire after ten minutes; account sessions last one day.</p><h2>Organisation membership</h2><p>An administrator assigned to a named organisation approves or revokes its members. The operator signs these records and holds the database and keys. This is an operator assertion about the administrator’s approval, not an organisation-held signature or proof of training or safety.</p><h2>A separate identity for each website</h2><p>Each website receives a different identifier and key. The operator can connect them to your account. Shared names and memberships can still make you recognisable.</p><h2>Withdrawal</h2><p>Disconnecting stops new access through this service. Copied information cannot be recalled. Signed membership statements expire within five minutes; websites must request current information when checking access.</p><h2>Retention and recovery</h2><p>Membership history and permission records remain until the operator removes them under the pilot’s retention agreement. Contact the operator for account removal or recovery. Backup copies follow the same agreement. Self-service deletion and account recovery beyond access to your email are not implemented.</p>`],
    developers:['Connect a WordPress website',`<p>Start on a staging copy. Keep ordinary WordPress sign-in available.</p><ol><li>Install OpenID Connect Generic Client and the Unanym companion supplied with this repository.</li><li>Send the operator your exact callback URL from Settings → Unanym.</li><li>Enter the issuer, client ID and private secret supplied by the operator.</li><li>Test email-code sign-in, your sharing choices, existing-account linking and disconnection.</li></ol><p>New WordPress accounts are Subscribers. Existing members connect from their WordPress profile after signing in normally. Accounts are never matched by email or name.</p><dl class="settings"><dt>Issuer</dt><dd><code>${issuer}</code></dd><dt>Contract</dt><dd><code>community-v1</code></dd><dt>Scopes</dt><dd><code>openid profile identity.v1 memberships.v1 offline_access</code></dd></dl><p>Membership statements name the organisation, operator signer, recipient and expiry. Sites explicitly choose which organisations to recognise. Sign-in alone does not grant membership access.</p><p>This standalone pilot has not had an independent security review. Public package distribution remains gated while it is rehearsed.</p>`]
  };
  const [title,body]=pages[section];
  return page(title,`<section class="narrow"><h1>${title}</h1>${body}</section>`,config);
}
