import {page} from './views.js';

// The illustrations are decorative: all their meaning is repeated in nearby text.
const drawing=(content)=>`<svg viewBox="0 0 280 150" aria-hidden="true" focusable="false" fill="none" xmlns="http://www.w3.org/2000/svg">${content}</svg>`;
const illustrations=[
 drawing('<path d="M140 69V105M140 105H54V120M140 105H226V120" stroke="#77907a" stroke-width="3"/><rect x="83" y="13" width="114" height="63" rx="18" fill="#225d4e"/><text x="140" y="53" text-anchor="middle" fill="white" font-size="20">FRRN</text><rect x="17" y="113" width="74" height="28" rx="7" fill="#e0e9d6"/><rect x="103" y="113" width="74" height="28" rx="7" fill="#e0e9d6"/><rect x="189" y="113" width="74" height="28" rx="7" fill="#e0e9d6"/><path d="M32 127h44m42 0h44m42 0h44" stroke="#56734f" stroke-width="3"/>'),
 drawing('<rect x="33" y="12" width="214" height="130" rx="14" fill="#fffef9" stroke="#a8b8a0"/><rect x="51" y="35" width="20" height="20" rx="4" fill="#225d4e"/><path d="m55 45 4 4 8-10" stroke="white" stroke-width="2"/><text x="84" y="51" fill="#203e37" font-size="19">Robin</text><rect x="51" y="75" width="20" height="20" rx="4" stroke="#77907a" stroke-width="2"/><path d="M84 85h130M51 118h137" stroke="#a8b8a0" stroke-width="5" stroke-linecap="round"/>'),
 drawing('<rect x="22" y="22" width="236" height="111" rx="14" fill="#fffef9" stroke="#a8b8a0"/><circle cx="53" cy="51" r="10" fill="#e0e9d6"/><path d="M76 51h139" stroke="#77907a" stroke-width="5" stroke-linecap="round"/><rect x="61" y="75" width="158" height="39" rx="8" fill="#f4e7da"/><text x="140" y="101" text-anchor="middle" fill="#734427" font-size="19">Disconnect</text>')
];

export function learnView(config) {
 return page('Try a practice connection',`<div class="learn">
 <section class="hero compact"><p class="eyebrow">A gentle introduction</p><h1>Your communities.<br><em>You choose what to share.</em></h1><p class="lead">FRRN is a shared sign-in for independent communities. It helps you visit different community websites and choose what each one learns about you.</p><a class="button" href="#practice">Try it with a practice account</a><p class="learn-small">No registration. No real personal details. Take your time.</p></section>
 <section aria-label="How it works" class="visual-story">
 <div class="learn-cards">
 <article data-scene="0">${illustrations[0]}<span class="learn-number">1</span><h2>One familiar sign-in</h2><p>Sign in through FRRN. Each community keeps its own website and rules.</p></article>
 <article data-scene="1">${illustrations[1]}<span class="learn-number">2</span><h2>Choose what to share</h2><p>Choose a name and, if you wish, a membership. The website receives no email address from FRRN.</p></article>
 <article data-scene="2">${illustrations[2]}<span class="learn-number">3</span><h2>Review or disconnect</h2><p>Manage your connections with FRRN. Disconnect to stop further access through this service.</p></article>
 </div>
 <div id="animation-controls" class="actions" hidden><button class="secondary" id="watch-story">Watch the steps</button><button class="secondary" id="next-scene">Next illustration</button><span id="story-caption" role="status">Read at your own pace, or watch the three steps.</span></div>
 </section>
 <section id="practice" class="practice" aria-labelledby="practice-title">
 <p class="eyebrow">Practice only · fictional account and website</p>
 <h2 id="practice-title">Have a go as Robin</h2><p>This is a pretend connection to “Garden community”. Your choices stay on this page. Nothing is sent to a community website or saved as a connection.</p>
 <noscript><p>The interactive practice needs JavaScript. The three illustrations above explain the same steps: sign in through FRRN, choose what to share, and manage the connection with FRRN.</p></noscript>
 <div id="practice-app" hidden>
 <p id="practice-progress" class="practice-location">Start · At the fictional community website</p>
 <div data-step="start"><h3 tabindex="-1">Welcome to Garden community</h3><p>On a connected website, this button takes you to FRRN to sign in.</p><button data-go="choose">Continue with FRRN</button></div>
 <div data-step="choose" hidden><h3 tabindex="-1">What may Garden community see?</h3><p>For this practice, Robin is already signed in to FRRN.</p><label for="practice-name">Your name on this website</label><select id="practice-name"><option>Robin</option><option>River</option></select><p class="learn-small">These are fictional names. In the real service, you can enter a first name or a pseudonym.</p>
 <fieldset><legend>Membership to share (optional)</legend><label class="choice"><input type="checkbox" id="practice-membership"><span>Meadow circle<small>A fictional membership for this practice</small></span></label></fieldset>
 <div class="practice-receipt" aria-live="polite"><h4>This website would receive</h4><ul><li>Name: <strong data-preview-name>Robin</strong></li><li>Its own member number for you</li><li data-preview-membership>No community memberships</li></ul><p>Your email and other memberships would not be shared.</p></div>
 <div class="actions"><button data-go="connected">Allow and continue</button><button class="secondary" data-go="start">Not now</button></div></div>
 <div data-step="connected" hidden><h3 tabindex="-1">Welcome, <span data-preview-name>Robin</span>.</h3><p>You have made a practice connection. Garden community would receive:</p><div class="practice-receipt"><ul><li>Name: <strong data-preview-name>Robin</strong></li><li>Its own member number for you</li><li data-preview-membership>No community memberships</li></ul><p>No email address from FRRN.</p></div><p>Next, find where you can stop this connection.</p><button data-go="manage">Manage what I share</button></div>
 <div data-step="manage" hidden><h3 tabindex="-1">My connections</h3><div class="practice-receipt"><p><strong>Garden community</strong> <span class="badge">Connected in practice</span></p><p>Name shared: <span data-preview-name>Robin</span></p><p data-preview-membership>No community memberships</p><button class="secondary" data-go="done">Disconnect</button></div><p>Disconnecting stops further access through FRRN. It does not erase information a website already received. Connected websites must check that permission is still current.</p><button class="secondary" data-go="choose">Change the practice choices</button></div>
 <div data-step="done" hidden><h3 tabindex="-1">Practice connection ended</h3><p>You chose what to share, reviewed the connection and disconnected it.</p><p>On a real website, disconnection stops further access through FRRN. Information already shared may remain with that website.</p><p><strong>Before trying it for real:</strong> could you explain what Garden community received, and where you went to disconnect?</p><div class="actions"><button class="secondary" id="restart-practice">Practise again</button><a class="button" href="/identity/example/">Try an example website →</a></div><p class="learn-small">The example asks for your permission. The local demonstration uses fictional accounts; the hosted example uses your Firn sign-in. Each community decides its own admission rules.</p></div>
 </div></section>
 <section class="learn-boundaries" aria-labelledby="know-title"><h2 id="know-title">A few things to know</h2><p><strong>A pseudonym is welcome.</strong> Your shared name or membership may still make you recognisable. This is not complete anonymity.</p><p><strong>frrn currently operates the service and holds the keys.</strong> Its operator can associate your connections. Community operation is a next step.</p><p><strong>Membership is not a safety guarantee.</strong> It does not confirm training. Training confirmations and personal trust choices are still planned.</p><p><a href="/identity/about">Read how your information is handled</a></p></section>
 <aside class="note"><div><h2>Do you look after a community website?</h2><p>The setup instructions have their own place.</p></div><a class="text-link" href="/identity/developers">Website setup →</a></aside>
 </div><script type="module" src="/identity/assets/learn.js"></script>`,config);
}
