import {displayName,developerURL} from './presentation.js';
export const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function page(title,body,config={}) {
  const base=config.basePath??'/identity';
  const {demo=false,contract}=config,brand=escape(displayName(config)),mark=brand==='FRRN'?'frrn':brand;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="robots" content="noindex,nofollow"><title>${escape(title)} · ${brand}</title><link rel="stylesheet" href="${base}/assets/style.css"></head><body${contract==='community-v1'?' class="standalone"':''}>
  <a class="skip" href="#main">Skip to content</a><header><a class="brand wordmark" href="${base}/" aria-label="${brand} home"><img src="${base}/assets/front-mark-light.svg" width="26" height="32" alt="">${mark}</a><nav aria-label="Account"><a href="${base}/sites">${contract==='community-v1'?'Your places':'My connections'}</a>${contract==='community-v1'?`<a href="${base}/records">Memberships</a>`:''}<a href="${contract==='community-v1'?base+'/account':'/'}">Your account</a></nav></header>
  ${demo?'<aside class="demo-banner">Local demonstration · fictional accounts and communities</aside>':''}
  <main id="main">${body}</main><footer><span>Your places. Your choice.</span><a href="${base}/about">Privacy</a><a href="${escape(developerURL(config))}">Identity by Unanym</a></footer></body></html>`;
}

export function consentView({config,client,uid,csrf,memberships,confirmations=[],allowConfirmations=false,previous,scopes}) {
  const base=config.basePath??'/identity';
  const standalone=config.contract==='community-v1';
  const shareMemberships=scopes.includes(standalone?'memberships.v1':'drop_memberships');
  return page('Choose what to share',`<section class="consent-space"><p class="consent-recipient">For <strong>${escape(client.name)}</strong> · ${escape(new URL(client.homepage).hostname)}</p><h1>Choose what to share</h1>
  <form method="post" action="${base}/interaction/${escape(uid)}/confirm"><input type="hidden" name="csrf" value="${escape(csrf)}">
  <div class="consent-flow"><div class="consent-you"><h2>You</h2><label for="display-name">Your name on this website</label><input id="display-name" name="name" autocomplete="nickname" maxlength="80" required value="${escape(previous?.name??'')}" aria-describedby="name-help"><p class="help" id="name-help">A first name or pseudonym is enough.</p>
  ${shareMemberships?`<fieldset><legend>Memberships <span class="optional">optional</span></legend>${memberships.length?memberships.map(m=>`<label class="choice"><input type="checkbox" name="memberships" value="${escape(m.slug)}" data-membership-name="${escape(m.name)}" ${previous?.memberships.includes(m.slug)?'checked':''}><span>${escape(m.name)}<small>${m.display_name?'Known here as '+escape(m.display_name):(standalone?'Approved membership':'Current community membership')}</small></span></label>`).join(''):'<p class="help">'+(standalone?'No approved memberships available to share.':'No current memberships to share.')+'</p>'}</fieldset>`:''}
  ${allowConfirmations&&scopes.includes('confirmations.v1')?`<fieldset><legend>Confirmations <span class="optional">optional</span></legend>${confirmations.length?confirmations.map(c=>`<label class="choice"><input type="checkbox" name="confirmations" value="${escape(c.slug)}" data-membership-name="${escape(c.name+' · '+c.organisation.name)}" ${previous?.confirmations?.includes(c.slug)?'checked':''}><span>${escape(c.name)}<small>Confirmed by ${escape(c.organisation.name)}</small></span></label>`).join(''):'<p class="help">No community confirmations available.</p>'}</fieldset>`:''}
  <div class="consent-kept"><strong>Not shared here</strong><p>Email · other memberships · session content</p></div></div>
  <section class="consent-site" aria-labelledby="recipient-title"><p class="eyebrow">This website receives</p><h2 id="recipient-title">${escape(client.name)}</h2><p class="destination">${escape(new URL(client.homepage).hostname)}</p><div class="consent-preview"><strong id="consent-preview-name">${escape(previous?.name??'Your chosen name')}</strong><p>A separate identifier for this website</p><ul id="consent-preview-memberships" hidden></ul><p id="consent-preview-empty" hidden>No memberships selected</p></div>
  <details class="consent-details"><summary>About this connection</summary><p class="help">${escape(client.description)}</p><p class="help">${standalone?(config.accountSource==='frrn'?'The community’s authorised organiser approved these memberships in FRRN. ':'The organisation’s assigned administrator approved these records. ')+escape(config.operatorName)+' signs them; this is not an organisation-held signature or proof of training.':(config.demo?'These fictional records simulate the hosted pilot.':'Memberships come from Firn’s database.')+' The service operator signs them; this is not an organisation’s independent confirmation or proof of training.'}</p></details></section>
  <div class="consent-bridge"><span class="consent-arrow" aria-hidden="true">→</span><button type="submit">Allow and continue</button><button class="secondary" type="submit" formnovalidate formaction="${base}/interaction/${escape(uid)}/cancel">Not now</button></div></div>
  ${scopes.includes('offline_access') && client.allow_refresh?'<p class="help">Stay signed in here for up to seven days. Disconnect at any time.</p>':''}
  <p class="help">The operator holds the keys and records this permission. This website decides whether to grant access.</p></form>
  <script type="module" src="${base}/assets/consent.js"></script></section>`,config);
}
export function sitesView(config,connections,csrf,selected) {
  const base=config.basePath??'/identity';
  if(config.contract==='community-v1')return page('Your places',placesBody(config,connections,csrf,selected),config);
  return page('My connections',`<section class="narrow"><p class="eyebrow">Your identity</p><h1>My connections</h1><p class="lead small">Each website sees only the information you chose for it.</p>${connections.length?connections.map(c=>`<article class="connection"><div class="connection-heading"><h2>${escape(c.site.name)}</h2><span class="badge">${c.active?'Connected':'Disconnected'}</span></div><p>Name shared: <strong>${escape(c.name)}</strong></p><p>${c.memberships.length?escape(c.memberships.join(', ')):'No community memberships shared.'}</p>${c.confirmations?.length?'<p>'+escape(c.confirmations.join(', '))+'</p>':''}<div class="actions"><a class="text-link" href="${escape(c.active?c.site.homepage:(c.site.sharing_uri??c.site.homepage))}">${c.active?'Visit website':'Connect again'} →</a>${c.active&&c.site.sharing_uri?`<a class="text-link" href="${escape(c.site.sharing_uri)}">Change sharing</a>`:''}${c.active?`<form method="post" action="${base}/sites/${escape(c.client)}/disconnect"><input type="hidden" name="csrf" value="${escape(csrf(c.client))}"><button class="secondary" type="submit">Disconnect</button></form>`:''}<a class="text-link" href="${base}/sites/${escape(c.client)}/receipt">Download my signed record</a></div></article>`).join(''):(config.contract==='community-v1'?'<div class="empty"><h2>No websites connected yet</h2><p>Choose Continue with '+escape(displayName(config))+' on your community website.</p></div>':'<div class="empty"><h2>No websites connected yet</h2><p>Try connecting the example website.</p><a class="button" href="'+base+'/example/">Try an example website</a></div>')}<p class="help">Disconnecting stops new access through this service. A website may retain information it already received; its own privacy and deletion rules still apply. Previously issued sign-in tokens expire within five minutes.</p></section>`,config);
}

function recordDate(value) {
  const date=new Date(value);
  return value&&Number.isFinite(date.getTime())?escape(date.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})):'';
}
function placesBody(config,{places},csrf,selected) {
  const base=config.basePath??'/identity';
  const selectedPlace=places.find(p=>p.client===selected)??places.find(p=>p.active)??places[0];
  return `<section class="places-space"><div class="places-intro"><div><p class="eyebrow">One place at a time</p><h1>Your places</h1><p class="lead small">Your name. Your sharing choices.</p></div><a class="text-link" href="${base}/records">Memberships & confirmations →</a></div>
  ${places.length?`<div class="places-grid">${places.map(p=>`<article class="connection place-card ${p.active?'':'place-disconnected'}" data-place="${escape(p.client)}"><div class="place-heading"><span class="place-symbol" aria-hidden="true">${escape(p.site.name.trim().slice(0,1).toUpperCase())}</span><div><h2>${escape(p.site.name)}</h2><p class="place-domain">${escape(new URL(p.site.homepage).host)}</p></div></div><div class="place-person"><span class="place-avatar" aria-hidden="true">${escape([...p.name.trim()][0]?.toUpperCase()??'·')}</span><div><span>${p.active?'Your name here':'Previously known as'}</span><strong>${escape(p.name)}</strong></div><span class="badge">${p.active?'Connected':'Disconnected'}</span></div>
  <div class="place-counts">${p.active?`${p.memberships.length} ${p.memberships.length===1?'membership':'memberships'} · ${p.confirmations.length} ${p.confirmations.length===1?'confirmation':'confirmations'}`:'Sharing stopped'}${p.unavailable?'<span class="place-changed">Some earlier choices are no longer available</span>':''}</div>
  <details class="place-sharing" name="place-sharing" ${p===selectedPlace?'open':''}><summary>${p.active?'What you share':'About this connection'}</summary><div class="place-details">
  ${p.active?`<h3>Memberships</h3>${p.memberships.length?`<ul class="place-records">${p.memberships.map(m=>`<li>${escape(m.name)}</li>`).join('')}</ul>`:'<p class="help">No memberships shared.</p>'}<h3>Confirmations</h3>${p.confirmations.length?`<ul class="place-records">${p.confirmations.map(c=>`<li>${escape(c.name)}<small>From ${escape(c.organisation)}</small></li>`).join('')}</ul>`:'<p class="help">No confirmations shared.</p>'}
  ${p.unavailable?'<p class="help">Unavailable records are not sent. Earlier choices can apply again if those records become available. Use Change sharing to review them.</p>':''}<p class="place-kept">Not shared here: email and your other connections.</p><p class="help">These are your sharing choices. The website decides what you can access.</p>`:'<p class="help">No new information is shared. The website may keep copies it already received.</p>'}
  <div class="actions">${p.active&&p.site.sharing_uri?`<a class="button" href="${escape(p.site.sharing_uri)}">Change sharing</a>`:''}${p.active?`<form method="post" action="${base}/sites/${escape(encodeURIComponent(p.client))}/disconnect"><input type="hidden" name="csrf" value="${escape(csrf(p.client))}"><button class="secondary" type="submit">Disconnect</button></form>`:''}</div>
  ${p.active&&!p.site.sharing_uri?'<p class="help">To change sharing, sign in again on this website.</p>':''}<details class="place-history"><summary>Connection record</summary><p class="help">Permission ${p.active?'updated':'stopped'} ${recordDate(p.updated)}.</p><a class="text-link" href="${base}/sites/${escape(encodeURIComponent(p.client))}/receipt">Download my signed record</a></details></div></details>
  <a class="place-visit" href="${escape(p.active?p.site.homepage:(p.site.sharing_uri??p.site.homepage))}">${p.active?'Open website':'Connect again'} <span aria-hidden="true">↗</span></a></article>`).join('')}</div>`:`<div class="empty places-empty"><h2>Your first connection starts at a website</h2><p>Choose <strong>Continue with ${escape(displayName(config))}</strong> on a website that uses this service. It will appear here after you choose what to share.</p>${config.clients?.some(c=>c.client_id==='example')?`<a class="button secondary" href="${base}/example/">Try the example website</a>`:''}</div>`}
  <details class="sharing-notes"><summary>Privacy & your records</summary><p>The operator can link your website identities to this account. Shared names or memberships can also make you recognisable to websites.</p><p>Disconnecting stops new access through this service. Websites may retain earlier copies; sign-in tokens already issued expire within five minutes.</p><a class="text-link" href="${base}/sharing-summary">Download sharing summary</a><p class="help">A readable record of these choices. It is not a key backup or a way to recover your account.</p><a href="${base}/about">How your information is handled</a></details></section>`;
}

export function recordsView(config,{memberships,confirmations}) {
  const base=config.basePath??'/identity';
  const cards=(records,type)=>records.length?`<div class="records-grid">${records.map(r=>`<article class="member-record"><p class="eyebrow">${type}</p><h3>${escape(r.name)}</h3><p class="record-source">${type==='Membership'?'Approved for':'Confirmed by'} ${escape(r.organisation)}</p><div class="record-destinations"><span>Shared with</span>${r.sharedWith.length?`<ul>${r.sharedWith.map(s=>`<li><a href="${base}/sites?place=${escape(encodeURIComponent(s.client))}">${escape(s.name)}</a></li>`).join('')}</ul>`:'<p>No websites</p>'}</div><details><summary>About this record</summary><p>${type==='Membership'?'An authorised administrator approved this membership.':'An authorised administrator recorded that this community’s introduction was completed. This does not certify professional training or safety.'}</p><p>${escape(config.operatorName)} signs the record. The organisation does not hold the signing key for this statement.</p>${recordDate(r.recordedAt)?`<p>Recorded ${recordDate(r.recordedAt)}.</p>`:''}<p>${r.validUntil?'Available until '+recordDate(r.validUntil)+'.':'No expiry set.'} The organisation can withdraw it.</p></details></article>`).join('')}</div>`:`<p class="records-empty">${type==='Membership'?'No approved memberships available to share.':'No community confirmations available to share.'}</p>`;
  return page('Memberships & confirmations',`<section class="places-space"><p class="eyebrow">Your community records</p><h1>Memberships<br>& confirmations</h1><p class="lead small">See where each record is shared.</p><section class="records-group"><h2>Memberships</h2>${cards(memberships,'Membership')}</section><section class="records-group"><h2>Confirmations</h2>${cards(confirmations,'Confirmation')}</section><p class="help">Only current records available to share appear here. A record can expire or be withdrawn. Each website decides which organisations and records it accepts.</p><a class="text-link" href="${base}/sites">Back to your places →</a></section>`,config);
}
export function about(config) {
  return page('How your information is handled',`<section class="narrow"><p class="eyebrow">A clear first version</p><h1>Your information,<br>one website at a time.</h1><h2>Your account stays at Firn</h2><p>This service uses your existing Firn account to sign in. This service reads whether your session is valid and which current memberships you may choose to share. It does not read your email or session content.</p><h2>A different identity for each website</h2><p>Each connected website receives its own identifier and website-specific public key. Your chosen name and shared information may still make you recognisable across websites. Firn can connect these identities to your account.</p><h2>What “signed” means</h2><p>This service records your sharing choices as signed events. Firn holds the signing keys on your behalf, encrypted at rest. A membership statement means only that Firn currently records that membership with current agreement consent. It does not certify training, endorse a person or guarantee safety.</p><h2>Change your mind</h2><p>Disconnect a website in My connections. Its current access tokens stop working. Information already copied by the website cannot be recalled; sign-in tokens already issued expire within five minutes.</p><h2>Stored records and deletion</h2><p>This service stores your website-specific keys, sharing choices, signed permission history and short-lived login records. Its history is retained while your Firn account exists. Deleting your Firn account removes its identity-service records during the next hourly cleanup. Operator backups may retain earlier copies until they expire.</p><h2>Who runs it</h2><p>This legacy adapter is retained for compatibility testing. The local demonstration uses fictional accounts. Use the standalone host for independently operated accounts and organisation administration.</p></section>`,config);
}

export function rehearsalView(config) {
  const base=config.basePath??'/identity';
  return page('A website rehearsal',`<section class="hero compact"><p class="eyebrow">WordPress · tested with fictional accounts</p><h1>A familiar sign-in.<br><em>Your existing website.</em></h1><p class="lead">Add Unanym, let a member choose what to share, and check that disconnecting ends access.</p><div class="actions"><a class="button" href="${base}/wordpress">Website setup</a><a class="button secondary" href="${base}/learn">Member practice</a></div></section>
  <section class="steps" aria-label="Rehearsal steps"><article><span class="number">01</span><h2>Connect the website</h2><p>Install the OIDC plugin and Unanym companion. Enter the operator’s connection details.</p></article><article><span class="number">02</span><h2>Choose what to share</h2><p>The member chooses a name and optional memberships. Existing accounts can be linked explicitly.</p></article><article><span class="number">03</span><h2>Check withdrawal</h2><p>Disconnect through Unanym. The website checks access on the next request.</p></article></section>
  <section class="narrow left"><h2>What the rehearsal established</h2><p>Automated tests exercised new and existing accounts, selective disclosure, withdrawal and restoration on another host. Real volunteer and member usability still needs testing.</p><p>This is an optional connection. A site keeps its ordinary administrator login and its own admission rules.</p></section>`,config);
}
